export const textsEn = [
  'about us',
  'services',
  'projects',
  'contact',
  'GPT Lab: The Kazakhstan-Based Data Science Powerhouse',
  'What is GPTLAB?',
  'GPT Lab is a team of experienced machine learning and data science experts, dedicated to delivering',
  'cutting-edge solutions to complex problems.',
  'Our passion for the field drives us to help businesses make',
  'data-driven decisions',
  "and push the boundaries of what's possible.",
  'How have we helped our clients?',
  'Improved Data Insights:',
  'We provide new insights into data to drive informed decision-making and business growth.',
  'Streamlined Operations:',
  'We streamline operations and increase efficiency through automation and optimization.',
  'Enhanced Customer Experiences:',
  'We enhance customer experiences through data-driven, personalized engagement.',
  'What do we',
  'do actually?',
  'At GPT Lab, we utilize the latest technology, like',
  'Generative Pre-trained Transformers (GPT),',
  'to solve complex data science and machine learning problems for various industries, adapting them to the power of GPT and delivering innovative solutions for business growth and success.',
  'What is our work',
  'process?',
  'Our work process involves',
  "understanding our client's needs,",
  'developing',
  'customized machine learning and data science solutions,',
  'working closely with our clients, delivering results that drive success, and providing',
  'an exceptional experience.',
  'Why us, though?',
  'Why settle for mediocrity when you can have the expertise of',
  "GPT Lab's data science wizards?",
  'With our love for technology and passion for delivering results,',
  "we're ready to cast a spell on your business challenges.",
  'Message us ',
  'Ready to',
  'talk to us?',
  'We can’t wait to hear about your ',
  'amazing idea.',
  'Feel free to',
  'drop us a line and get a',
  'free quote',
  'from us.',
  'I want to connect',
  'now ready to connect?',
];

export const textsRU = [
  'о нас',
  'услуги',
  'проекты',
  'контакты',
  'GPT Lab: Казахстанский центр обработки данных',
  'Что такое GPTLAB?',
  'GPT Lab - это команда опытных экспертов в области машинного обучения и науки о данных, нацеленных на предоставление',
  'передовые решения сложных проблем',
  'Наша страсть к этой области побуждает нас помогать бизнесу принимать решения',
  'решения, основанные на данных',
  'и раздвигать границы возможного',
  'Как мы помогли нашим клиентам?',
  'Улучшенная аналитика данных:',
  'Мы предоставляем новые возможности для анализа данных, способствующие принятию обоснованных решений и росту бизнеса',
  'Оптимизированные операции:',
  'Мы оптимизируем операции и повышаем эффективность за счет автоматизации и оптимизации.',
  'Улучшенное взаимодействие с клиентами:',
  'Мы улучшаем взаимодействие с клиентами за счет персонализированного взаимодействия, основанного на данных.',
  'Что мы делаем',
  'делаем на самом деле?',
  'В GPT Lab мы используйте новейшие технологии, такие как ',
  'Генеративные предварительно обученные трансформаторы (GPT)',
  'для решения сложных задач обработки данных и машинного обучения в различных отраслях промышленности, адаптируя их к возможностям GPT и предоставляя инновационные решения для роста и успеха бизнеса',
  'В чем заключается наша работа',
  'процесс?',
  'Наш рабочий процесс включает в себя',
  'понимание потребностей наших клиентов',
  'разработка',
  'индивидуальные решения для машинного обучения и науки о данных',
  'тесное сотрудничество с нашими клиентами, достижение результатов, способствующих успеху, и предоставление',
  'исключительный опыт',
  'Но почему именно мы?',
  'Зачем соглашаться на посредственность, когда вы можете обладать опытом',
  'Волшебники в области науки о данных GPT Lab?',
  'С нашей любовью к технологиям и стремлением к достижению результатов',
  'мы готовы решить все ваши бизнес-задачи',
  'Напишите нам',
  'Готовы',
  'поговорите с нами?',
  'Нам не терпится услышать о вашей ',
  'потрясающая идея',
  'Не стесняйтесь',
  'напишите нам и получите',
  'бесплатное предложение',
  'от нас',
  'Я хочу подключиться',
  'теперь готовы подключиться?',
];

export const textsKZ = [
  'about usKZ',
  'services',
  'projects',
  'contact',
  'GPT Lab: The Kazakhstan-Based Data Science Powerhouse',
  'What is GPTLAB?',
  'GPT Lab is a team of experienced machine learning and data science experts, dedicated to delivering',
  'cutting-edge solutions to complex problems.',
  'Our passion for the field drives us to help businesses make',
  'data-driven decisions',
  "and push the boundaries of what's possible.",
  'How have we helped our clients?',
  'Improved Data Insights:',
  'We provide new insights into data to drive informed decision-making and business growth.',
  'Streamlined Operations:',
  'We streamline operations and increase efficiency through automation and optimization.',
  'Enhanced Customer Experiences:',
  'We enhance customer experiences through data-driven, personalized engagement.',
  'What do we',
  'do actually?',
  'At GPT Lab, we utilize the latest technology, like',
  'Generative Pre-trained Transformers (GPT),',
  'to solve complex data science and machine learning problems for various industries, adapting them to the power of GPT and delivering innovative solutions for business growth and success.',
  'What is our work',
  'process?',
  'Our work process involves',
  "understanding our client's needs,",
  'developing',
  'customized machine learning and data science solutions,',
  'working closely with our clients, delivering results that drive success, and providing',
  'an exceptional experience.',
  'Why us, though?',
  'Why settle for mediocrity when you can have the expertise of',
  "GPT Lab's data science wizards?",
  'With our love for technology and passion for delivering results,',
  "we're ready to cast a spell on your business challenges.",
  'Message us ',
  'Ready to',
  'talk to us?',
  'We can’t wait to hear about your ',
  'amazing idea.',
  'Feel free to',
  'drop us a line and get a',
  'free quote',
  'from us.',
  'I want to connect',
  'now ready to connect?',
];
