export const textsEn = [
  'about us',
  'services',
  'projects',
  'contact',
  'OUR PROJECTS',
  'IN THE MAKING',
  'Open for new project',
  'We would love to know about your project.',
  'Feel free to drop us a line',
  'tell us about your project',
  'EEG-based AI model for post-stroke rehabilitation',
  'MAY 1, 2020 - NOV 3O, 2020',
  'EEG-based AI model for post-stroke rehabilitation',
  "Our R&D project involved the creation of an AI model that could read EEG signals to support post-stroke rehabilitation by aiding prosthetic hand movement. The model's accuracy was achieved by training it with a diverse dataset and implementing advanced machine learning algorithms.",
  '#AI',
  '#MachineLearning',
  '#Neuroscience',
  'Reinforcement Learning for Vehicle Routing',
  'JAN 1, 2022 - JULY 31, 2023',
  'Reinforcement Learning for Vehicle Routing',
  'Using reinforcement learning models, we were able to solve a complex vehicle routing problem for our logistics client. The AI models optimized the delivery routes to reduce transportation costs, increase efficiency, and improve customer satisfaction.',
  '#ReinforcementLearning',
  '#Optimization',
  '#Logistics',
  'Data Lake for Coal Mining Facility',
  'AUG 1, 2020 - DEC 31, 2021',
  'Data Lake for Coal Mining Facility',
  "Our team created a data lake for a coal mining facility that collected data from sensors throughout the facility, allowing for real-time monitoring and analysis of the facility's performance. This allowed for improved decision-making, predictive maintenance, and overall optimization of operations.",
  '#BigData',
  '#Sensors',
  '#RealTimeMonitoring',
  'Object Detection for Construction Site Safety',
  'MAR 1, 2021 - SEP 30, 2022',
  'Object Detection for Construction Site Safety',
  'We developed an object detection algorithm to monitor safety measures at construction sites. The algorithm detected potential hazards, such as workers not wearing proper safety gear, and alerted management in real-time to ensure a safe working environment.',
  '#ComputerVision',
  '#Safety',
  '#RealTimeAlerts',
  'Talent Sharing for Telematics Project',
  'NOV 1, 2020 - APR 30, 2022',
  'Talent Sharing for Telematics Project',
  "Our talent-sharing service provided a dedicated team of data scientists to support our client's telematics project. The team utilized machine learning algorithms to process large volumes of data, providing valuable insights to improve the client's business operations.",
  '#DataScience',
  '#MachineLearning',
  '#BusinessIntelligence',
  'Machine Learning for Algo-Trading',
  'JULY 1, 2021 - JAN 31, 2023',
  'Machine Learning for Algo-Trading',
  'We developed a machine learning system for an algo-trading company that analyzed market trends and made informed trading decisions. The system was trained with historical market data, which allowed for increased accuracy in predicting market trends and better decision-making.',
  '#Finance',
  '#PredictionModels',
  '#MarketTrends',
  'Object Detection for Road Quality Assurance',
  'OCT 1, 2020 - JUNE 30, 2021',
  'Object Detection for Road Quality Assurance',
  'Our team developed an object detection algorithm that could detect cracks on the road, allowing for more accurate road quality assurance. This enabled timely repairs, reduced maintenance costs, and overall improved road safety for drivers.',
  '#ComputerVision',
  '#Infrastructure',
  '#Maintenance',
  'contact us',
  'Ready to',
  'talk to us?',
  'We can’t wait to hear about your ',
  'amazing idea.',
  'Feel free to drop us a line and get a',
  'free quote',
  'from us.',
  'I want to connect',
  'now ready to connect?',
];

export const textsRu = [
  'о нас',
  'услуги',
  'проекты',
  'контакты',
  'НАШИ ПРОЕКТЫ',
  'В РАЗРАБОТКЕ',
  'Открыт для нового проекта',
  'Мы будем рады узнать о вашем проекте',
  'Не стесняйтесь, напишите нам',
  'расскажите нам о своем проекте',
  'Модель ИИ на основе ЭЭГ для реабилитации после инсульта',
  '1 МАЯ 2020 - 3 НОЯБРЯ 2020',
  'модель ИИ на основе ЭЭГ для реабилитации после инсульта',
  'Наш научно-исследовательский проект включал создание модели искусственного интеллекта, которая могла бы считывать сигналы ЭЭГ для поддержки реабилитации после инсульта, помогая протезу руки двигаться. Точность модели была достигнута путем ее обучения на разнообразном наборе данных и применения передовых алгоритмов машинного обучения',
  '#AI',
  '#MachineLearning',
  '#Neuroscience',
  'Reinforcement Learning for Vehicle Routing',
  '1 ЯНВАРЯ 2022 - 31 ИЮЛЯ 2023',
  'Reinforcement Learning for Vehicle Routing',
  'Используя модели обучения с подкреплением, мы смогли решить сложную проблему маршрутизации транспортных средств для нашего логистического клиента. Модели ИИ оптимизировали маршруты доставки, чтобы снизить транспортные расходы, повысить эффективность и удовлетворенность клиентов.',
  '#ReinforcementLearning',
  '#Оптимизация',
  '#Logistics',
  'Озеро данных для предприятия по добыче угля',
  'AUG 1, 2020 - DEC 31, 2021',
  'Озеро данных для предприятия по добыче угля',
  'Наша команда создала озеро данных для угледобывающего предприятия, которое собирало данные с датчиков по всему предприятию, обеспечивая мониторинг и анализ работы предприятия в режиме реального времени. Это позволило улучшить процесс принятия решений, предиктивного обслуживания и общей оптимизации операций',
  '#BigData',
  '#Sensors',
  '#RealTimeMonitoring',
  'Обнаружение объектов для обеспечения безопасности на строительных площадках',
  '1 МАРТА 2021 - 30 СЕНТЯБРЯ 2022',
  'Обнаружение объектов для безопасности строительных площадок',
  'Мы разработали алгоритм обнаружения объектов для мониторинга мер безопасности на строительных площадках. Алгоритм обнаруживает потенциальные опасности, такие как рабочие, не надевшие надлежащее защитное снаряжение, и предупреждает руководство в режиме реального времени, чтобы обеспечить безопасные условия труда.',
  '#ComputerVision',
  '#Safety',
  '#RealTimeAlerts',
  'Talent Sharing for Telematics Project',
  'NOV 1, 2020 - APR 30, 2022',
  'Talent Sharing for Telematics Project',
  'Наша служба совместного использования талантов предоставила выделенную команду специалистов по анализу данных для поддержки телематического проекта нашего клиента. Команда использовала алгоритмы машинного обучения для обработки больших объемов данных, предоставляя ценные сведения для улучшения бизнес-операций клиента.',
  '#DataScience',
  '#MachineLearning',
  '#BusinessIntelligence',
  'Machine Learning for Algo-Trading',
  'JULY 1, 2021 - JAN 31, 2023',
  'Machine Learning for Algo-Trading',
  'Мы разработали систему машинного обучения для компании, занимающейся альго-трейдингом, которая анализировала рыночные тенденции и принимала обоснованные торговые решения. Система была обучена на исторических рыночных данных, что позволило повысить точность прогнозирования рыночных тенденций и улучшить процесс принятия решений.',
  '#Finance',
  '#PredictionModels',
  '#MarketTrends',
  'Обнаружение объектов для обеспечения качества дорог',
  '1 ОКТЯБРЯ 2020 - 30 ИЮНЯ 2021',
  'Обнаружение объектов для обеспечения качества дорог',
  'Наша команда разработала алгоритм обнаружения объектов, который позволяет обнаружить трещины на дороге, что дает возможность более точного контроля качества дорог. Это позволило своевременно проводить ремонт, снизить затраты на обслуживание и в целом повысить безопасность дорожного движения для водителей.',
  '#ComputerVision',
  '#Инфраструктура',
  '#Maintenance',
  'свяжитесь с нами',
  'Готовы',
  'поговорить с нами?',
  'Мы не можем дождаться, чтобы услышать о вашей ',
  'удивительной идее.',
  'Не стесняйтесь, напишите нам и получите',
  'бесплатное предложение',
  'от нас.',
  'Я хочу подключиться',
  'теперь готовы подключиться?',
];

export const textsKz = [
  'about usKZ',
  'services',
  'projects',
  'contact',
  'OUR PROJECTS',
  'IN THE MAKING',
  'Open for new project',
  'We would love to know about your project.',
  'Feel free to drop us a line',
  'tell us about your project',
  'EEG-based AI model for post-stroke rehabilitation',
  'MAY 1, 2020 - NOV 3O, 2020',
  'EEG-based AI model for post-stroke rehabilitation',
  "Our R&D project involved the creation of an AI model that could read EEG signals to support post-stroke rehabilitation by aiding prosthetic hand movement. The model's accuracy was achieved by training it with a diverse dataset and implementing advanced machine learning algorithms.",
  '#AI',
  '#MachineLearning',
  '#Neuroscience',
  'Reinforcement Learning for Vehicle Routing',
  'JAN 1, 2022 - JULY 31, 2023',
  'Reinforcement Learning for Vehicle Routing',
  'Using reinforcement learning models, we were able to solve a complex vehicle routing problem for our logistics client. The AI models optimized the delivery routes to reduce transportation costs, increase efficiency, and improve customer satisfaction.',
  '#ReinforcementLearning',
  '#Optimization',
  '#Logistics',
  'Data Lake for Coal Mining Facility',
  'AUG 1, 2020 - DEC 31, 2021',
  'Data Lake for Coal Mining Facility',
  "Our team created a data lake for a coal mining facility that collected data from sensors throughout the facility, allowing for real-time monitoring and analysis of the facility's performance. This allowed for improved decision-making, predictive maintenance, and overall optimization of operations.",
  '#BigData',
  '#Sensors',
  '#RealTimeMonitoring',
  'Object Detection for Construction Site Safety',
  'MAR 1, 2021 - SEP 30, 2022',
  'Object Detection for Construction Site Safety',
  'We developed an object detection algorithm to monitor safety measures at construction sites. The algorithm detected potential hazards, such as workers not wearing proper safety gear, and alerted management in real-time to ensure a safe working environment.',
  '#ComputerVision',
  '#Safety',
  '#RealTimeAlerts',
  'Talent Sharing for Telematics Project',
  'NOV 1, 2020 - APR 30, 2022',
  'Talent Sharing for Telematics Project',
  "Our talent-sharing service provided a dedicated team of data scientists to support our client's telematics project. The team utilized machine learning algorithms to process large volumes of data, providing valuable insights to improve the client's business operations.",
  '#DataScience',
  '#MachineLearning',
  '#BusinessIntelligence',
  'Machine Learning for Algo-Trading',
  'JULY 1, 2021 - JAN 31, 2023',
  'Machine Learning for Algo-Trading',
  'We developed a machine learning system for an algo-trading company that analyzed market trends and made informed trading decisions. The system was trained with historical market data, which allowed for increased accuracy in predicting market trends and better decision-making.',
  '#Finance',
  '#PredictionModels',
  '#MarketTrends',
  'Object Detection for Road Quality Assurance',
  'OCT 1, 2020 - JUNE 30, 2021',
  'Object Detection for Road Quality Assurance',
  'Our team developed an object detection algorithm that could detect cracks on the road, allowing for more accurate road quality assurance. This enabled timely repairs, reduced maintenance costs, and overall improved road safety for drivers.',
  '#ComputerVision',
  '#Infrastructure',
  '#Maintenance',
  'contact us',
  'Ready to',
  'talk to us?',
  'We can’t wait to hear about your ',
  'amazing idea.',
  'Feel free to drop us a line and get a',
  'free quote',
  'from us.',
  'I want to connect',
  'now ready to connect?',
];
