export const textsEn = [
  'about us',
  'services',
  'projects',
  'contact',
  'FIXED COST',
  'PROJECTS',
  'Price Based on Project Type',
  'Initial deposit up front and then payments made after each milestone is complete',
  'Data Lake Creation',
  'Data Architects, Data Flow automatization, Master Data',
  'Data Processing',
  'Data Engineers, pipelining, data cleaning',
  'Modelling',
  'Data Scientists, Data Analysts, build and train',
  'Deployment',
  'ML-ops, Infrastructure engineers',
  'Website',
  'Full-stack Engineers, front-end and back-end',
  'UI - UX Design',
  'Designer, Design flow, user journey',
  'tell us about your project',
  'HIRE US AS',
  'YOUR TEAM',
  'Save at least',
  ' $100,000 a year!',
  'One',
  'senior designer',
  'and one',
  'senior engineer',
  'will cost you a minimum of',
  '$250,000',
  'per year plus benefits, if you can find one who is available!',
  'Dedicated Data',
  'Science Team:',
  'Category: ',
  'AI Implementation Services',
  'Description:',
  'Providing a dedicated team of experienced Data Scientists to work exclusively on implementing AI technologies for our clients.',
  'Small Project:',
  '$15,000 - $30,000 per year',
  'Medium Project:',
  '$30,000 - $60,000 per year',
  'Large Project:',
  '$60,000 - $100,000 per year',
  'contact us',
  'Project',
  'Development:',
  'Category:',
  'Software Development Services',
  'Description:',
  'Providing full-cycle development services, including project planning, design, development, testing, and deployment.',
  'Small Project:',
  '$30,000 - $50,000',
  'Medium Project:',
  '$50,000 - $100,000',
  'Large Project:',
  '$100,000 - $250,000',
  'contact us',
  'Engineering',
  'Staffing:',
  'Category: ',
  'Staffing Solutions',
  'Description',
  'Renting experienced engineers to work on-site or remotely for short or long-term projects.',
  'Junior Engineer:',
  '$3,000 - $5,000 per month',
  'Middle Engineer:',
  '$5,000 - $7,000 per month',
  'Senior Engineer:',
  '$7,000 - $10,000 per month',
  'contact us',
  'The actual pricing may vary based on various factors such as project complexity, project duration, and the skills and experience of the team members.',
  'Ready to',
  'talk to us?',
  'We can’t wait to hear about your ',
  'amazing idea.',
  'Feel free to drop us a line and get a',
  'free quote',
  'from us.',
  'I want to connect',
  'now ready to connect?',
];

export const textsRU = [
  'about usRU',
  'услуги',
  'проекты',
  'контакт',
  'ФИКСИРОВАННАЯ СТОИМОСТЬ',
  'PROJECTS',
  'Цена в зависимости от типа проекта',
  'Первоначальный аванс и последующие выплаты после завершения каждого этапа',
  'Создание озера данных',
  'Архитекторы данных, автоматизация потоков данных, мастер-данные',
  'Обработка данных',
  'Data Engineers, конвейеризация, очистка данных',
  'Моделирование',
  'Data Scientists, Data Analysts, создание и обучение',
  'Развертывание',
  'ML-опы, инженеры инфраструктуры',
  'Website',
  'Full-stack инженеры, front-end и back-end',
  'UI - UX Design',
  'Дизайнер, проектирование потока, пользовательский путь',
  'расскажите нам о вашем проекте',
  'НАЙМИТЕ НАС КАК',
  'ВАША КОМАНДА',
  'Экономия не менее',
  '$100,000 в год!',
  '1',
  'старший дизайнер',
  'и один',
  'старший инженер',
  'обойдется вам минимум в',
  '$250,000',
  'в год плюс льготы, если вы сможете найти свободного человека!',
  'Выделенные данные',
  'Научная команда:',
  'Категория: ',
  'Услуги по внедрению искусственного интеллекта',
  'Описание:',
  'Предоставление выделенной команды опытных Data Scientists для работы исключительно над внедрением технологий искусственного интеллекта для наших клиентов.',
  'Описание:',
  'Небольшой проект:',
  '$15 000 - $30 000 в год',
  'Средний проект:',
  '$30 000 - $60 000 в год',
  'Крупный проект:',
  '$60,000 - $100,000 в год',
  'свяжитесь с нами',
  'Проект',
  'Разработка:',
  'Категория:',
  'Услуги по разработке программного обеспечения',
  'Описание:',
  'Предоставление услуг по разработке полного цикла, включая планирование проекта, проектирование, разработку, тестирование и развертывание.',
  'Малый проект:',
  '$30,000 - $50,000',
  'Средний проект:',
  '$50,000 - $100,000',
  'Крупный проект:',
  '$100,000 - $250,000',
  'свяжитесь с нами',
  'Инжиниринг',
  'Подбор персонала:',
  'Категория: ',
  'Кадровые решения',
  'Описание',
  'Аренда опытных инженеров для работы на месте или удаленно для краткосрочных или долгосрочных проектов.',
  'Младший инженер:',
  '$3,000 - $5,000 в месяц',
  'Средний инженер:',
  '$5 000 - $7 000 в месяц',
  'Старший инженер:',
  '$7,000 - $10,000 в месяц',
  'свяжитесь с нами',
  'Фактическая цена может варьироваться в зависимости от различных факторов, таких как сложность проекта, продолжительность проекта, а также навыки и опыт членов команды.',
  'Готовы',
  'поговорить с нами?',
  'Мы не можем дождаться, чтобы услышать о вашей ',
  'удивительной идее.',
  'Не стесняйтесь, напишите нам и получите',
  'бесплатное предложение',
  'от нас.',
  'Я хочу подключиться',
  'теперь готовы подключиться?',
];

export const textsKZ = [
  'about usKZ',
  'services',
  'projects',
  'contact',
  'FIXED COST',
  'PROJECTS',
  'Price Based on Project Type',
  'Initial deposit up front and then payments made after each milestone is complete',
  'Data Lake Creation',
  'Data Architects, Data Flow automatization, Master Data',
  'Data Processing',
  'Data Engineers, pipelining, data cleaning',
  'Modelling',
  'Data Scientists, Data Analysts, build and train',
  'Deployment',
  'ML-ops, Infrastructure engineers',
  'Website',
  'Full-stack Engineers, front-end and back-end',
  'UI - UX Design',
  'Designer, Design flow, user journey',
  'tell us about your project',
  'HIRE US AS',
  'YOUR TEAM',
  'Save at least',
  ' $100,000 a year!',
  'One',
  'senior designer',
  'and one',
  'senior engineer',
  'will cost you a minimum of',
  '$250,000',
  'per year plus benefits, if you can find one who is available!',
  'Dedicated Data',
  'Science Team:',
  'Category: ',
  'AI Implementation Services',
  'Description:',
  'Providing a dedicated team of experienced Data Scientists to work exclusively on implementing AI technologies for our clients.',
  'Small Project:',
  '$15,000 - $30,000 per year',
  'Medium Project:',
  '$30,000 - $60,000 per year',
  'Large Project:',
  '$60,000 - $100,000 per year',
  'contact us',
  'Project',
  'Development:',
  'Category:',
  'Software Development Services',
  'Description:',
  'Providing full-cycle development services, including project planning, design, development, testing, and deployment.',
  'Small Project:',
  '$30,000 - $50,000',
  'Medium Project:',
  '$50,000 - $100,000',
  'Large Project:',
  '$100,000 - $250,000',
  'contact us',
  'Engineering',
  'Staffing:',
  'Category: ',
  'Staffing Solutions',
  'Description',
  'Renting experienced engineers to work on-site or remotely for short or long-term projects.',
  'Junior Engineer:',
  '$3,000 - $5,000 per month',
  'Middle Engineer:',
  '$5,000 - $7,000 per month',
  'Senior Engineer:',
  '$7,000 - $10,000 per month',
  'contact us',
  'The actual pricing may vary based on various factors such as project complexity, project duration, and the skills and experience of the team members.',
  'Ready to',
  'talk to us?',
  'We can’t wait to hear about your ',
  'amazing idea.',
  'Feel free to drop us a line and get a',
  'free quote',
  'from us.',
  'I want to connect',
  'now ready to connect?',
];
